from __future__ import annotations

import pytest

from carrel.models import ConvertTool, Sensitivity, TranscribeTool
from carrel.policy.sensitivity import PolicyDecision, select_tool


@pytest.mark.parametrize(
    (
        "name",
        "requested_tool",
        "available_tools",
        "sensitivity",
        "cloud_consent",
        "tool_class",
        "expected_selected",
        "expected_rationale",
    ),
    [
        (
            "high explicit local available",
            ConvertTool.LITEPARSE,
            [ConvertTool.LITEPARSE, ConvertTool.MINERU],
            Sensitivity.HIGH,
            False,
            "convert",
            ConvertTool.LITEPARSE,
            "Requested local tool is available; preference honored",
        ),
        (
            "high explicit local missing",
            ConvertTool.LITEPARSE,
            [ConvertTool.MINERU],
            Sensitivity.HIGH,
            True,
            "convert",
            None,
            "HIGH sensitivity requires local; local tool missing; install and retry",
        ),
        (
            "high explicit cloud blocked",
            ConvertTool.MINERU,
            [ConvertTool.LITEPARSE, ConvertTool.MINERU],
            Sensitivity.HIGH,
            True,
            "convert",
            None,
            "HIGH sensitivity blocks cloud tools regardless of consent",
        ),
        (
            "high default local",
            None,
            [ConvertTool.LITEPARSE, ConvertTool.MINERU],
            Sensitivity.HIGH,
            True,
            "convert",
            ConvertTool.LITEPARSE,
            "Local tool selected by default",
        ),
        (
            "high default missing local",
            None,
            [ConvertTool.MINERU],
            Sensitivity.HIGH,
            True,
            "convert",
            None,
            "HIGH sensitivity requires local; local tool missing; install and retry",
        ),
        (
            "medium explicit local available",
            TranscribeTool.COLI,
            [TranscribeTool.COLI, TranscribeTool.GROQ],
            Sensitivity.MEDIUM,
            False,
            "transcribe",
            TranscribeTool.COLI,
            "Requested local tool is available; preference honored",
        ),
        (
            "medium explicit local missing",
            TranscribeTool.COLI,
            [TranscribeTool.GROQ],
            Sensitivity.MEDIUM,
            True,
            "transcribe",
            None,
            "Local tool missing; to use cloud, run with `--tool <cloud>`",
        ),
        (
            "medium explicit cloud allowed",
            TranscribeTool.GROQ,
            [TranscribeTool.COLI],
            Sensitivity.MEDIUM,
            False,
            "transcribe",
            TranscribeTool.GROQ,
            "Explicit cloud tool request counts as consent",
        ),
        (
            "medium default local",
            None,
            [TranscribeTool.YOUTUBE_CAPTIONS, TranscribeTool.GEMINI],
            Sensitivity.MEDIUM,
            True,
            "transcribe",
            TranscribeTool.YOUTUBE_CAPTIONS,
            "Local tool selected by default",
        ),
        (
            "medium default missing local",
            None,
            [TranscribeTool.GEMINI],
            Sensitivity.MEDIUM,
            True,
            "transcribe",
            None,
            "Local tool missing; to use cloud, run with `--tool <cloud>`",
        ),
        (
            "low explicit cloud with consent",
            ConvertTool.MINERU,
            [ConvertTool.LITEPARSE],
            Sensitivity.LOW,
            True,
            "convert",
            ConvertTool.MINERU,
            "Explicit cloud tool request counts as consent",
        ),
        (
            "low explicit local auto routes with consent",
            ConvertTool.LITEPARSE,
            [ConvertTool.MINERU],
            Sensitivity.LOW,
            True,
            "convert",
            ConvertTool.MINERU,
            "Requested local tool unavailable; cloud consent enabled so routing to cloud",
        ),
        (
            "low default local with consent",
            None,
            [ConvertTool.LITEPARSE, ConvertTool.MINERU],
            Sensitivity.LOW,
            True,
            "convert",
            ConvertTool.LITEPARSE,
            "Local tool selected by default",
        ),
        (
            "low default cloud with consent",
            None,
            [ConvertTool.MINERU],
            Sensitivity.LOW,
            True,
            "convert",
            ConvertTool.MINERU,
            "No local tool available; cloud consent enabled so routing to cloud",
        ),
        (
            "low explicit cloud without consent still allowed",
            TranscribeTool.GROQ,
            [TranscribeTool.COLI],
            Sensitivity.LOW,
            False,
            "transcribe",
            TranscribeTool.GROQ,
            "Explicit cloud tool request counts as consent",
        ),
        (
            "low default missing local without consent",
            None,
            [TranscribeTool.GROQ],
            Sensitivity.LOW,
            False,
            "transcribe",
            None,
            "Local tool missing; to use cloud, set cloud_consent=True or run with `--tool <cloud>`",
        ),
    ],
    ids=lambda case: case,
)
def test_select_tool_matrix(
    name: str,
    requested_tool: ConvertTool | TranscribeTool | None,
    available_tools: list[ConvertTool | TranscribeTool],
    sensitivity: Sensitivity,
    cloud_consent: bool,
    tool_class: str,
    expected_selected: ConvertTool | TranscribeTool | None,
    expected_rationale: str,
) -> None:
    decision = select_tool(
        requested_tool=requested_tool,
        available_tools=available_tools,
        sensitivity=sensitivity,
        cloud_consent=cloud_consent,
        tool_class=tool_class,  # type: ignore[arg-type]
    )

    assert isinstance(decision, PolicyDecision)
    assert decision.selected_tool == expected_selected, name
    assert decision.rationale == expected_rationale, name
